# Application Name & Port
spring.application.name=connect-frontend-with-backend
server.port=${PORT:8082}

# MySQL Database Configuration
spring.datasource.url=${url}
spring.datasource.username=${username}
spring.datasource.password=${password}

# MySQL Driver
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Settings
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true